@startuml


class Controller {
Adapter adapter
}

class BaseAdapter {

}

class RegressionAdapter {
   RegressionEngine regressionEngine
   getLiveEntries()
}
note top: for each entry (currently only one tested),\n return new WowzaStreamInfo

class RegressionEngine {
 EntryInfo[] entries
 hlsStreamRegressionValidator[] validators
}

class EntryInfo {

}
note bottom: regression entries config

class hlsStreamRegressionValidator {
     this_run_results {}
     regression_results_db {}
     ValidateRegressionResults()
}

class RegressionConfig {

}

Controller --> RegressionAdapter
BaseAdapter <|-- RegressionAdapter
RegressionAdapter --> RegressionEngine

EntryInfo <--* RegressionEngine
hlsStreamRegressionValidator <--* RegressionEngine


@enduml