@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection

class PlaylistGenerator {
    entryId
    isNewSession
    streamInfo
    flavorsObjArray
    logger
    entryServerNodeId
    entryServerType
}

List <|-- PlaylistGenerator
'Collection <|-- AbstractCollection

'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

@enduml