// generated by generateBitFieldMacros.py from mpegTsStructs.def
#ifndef __MPEGTSSTRUCTS_H__
#define __MPEGTSSTRUCTS_H__

// mpeg_ts_header
typedef unsigned char mpeg_ts_header_t;

#define mpeg_ts_header_get_syncByte(x) (((x)[0]))
#define mpeg_ts_header_set_syncByte(x, v) { (x)[0] = ((v) & 0xff); }
#define mpeg_ts_header_get_transportErrorIndicator(x) (((((x)[1]) & 0x80) >> 7))
#define mpeg_ts_header_set_transportErrorIndicator(x, v) { (x)[1] = (((x)[1]) & 0x7f) | (((v) << 7) & 0x80); }
#define mpeg_ts_header_get_payloadUnitStartIndicator(x) (((((x)[1]) & 0x40) >> 6))
#define mpeg_ts_header_set_payloadUnitStartIndicator(x, v) { (x)[1] = (((x)[1]) & 0xbf) | (((v) << 6) & 0x40); }
#define mpeg_ts_header_get_transportPriority(x) (((((x)[1]) & 0x20) >> 5))
#define mpeg_ts_header_set_transportPriority(x, v) { (x)[1] = (((x)[1]) & 0xdf) | (((v) << 5) & 0x20); }
#define mpeg_ts_header_get_PID(x) (((((x)[1]) & 0x1f) << 8) | ((x)[2]))
#define mpeg_ts_header_set_PID(x, v) { (x)[1] = (((x)[1]) & 0xe0) | (((v) >> 8) & 0x1f); (x)[2] = ((v) & 0xff); }
#define mpeg_ts_header_get_scramblingControl(x) (((((x)[3]) & 0xc0) >> 6))
#define mpeg_ts_header_set_scramblingControl(x, v) { (x)[3] = (((x)[3]) & 0x3f) | (((v) << 6) & 0xc0); }
#define mpeg_ts_header_get_adaptationFieldExist(x) (((((x)[3]) & 0x20) >> 5))
#define mpeg_ts_header_set_adaptationFieldExist(x, v) { (x)[3] = (((x)[3]) & 0xdf) | (((v) << 5) & 0x20); }
#define mpeg_ts_header_get_containsPayload(x) (((((x)[3]) & 0x10) >> 4))
#define mpeg_ts_header_set_containsPayload(x, v) { (x)[3] = (((x)[3]) & 0xef) | (((v) << 4) & 0x10); }
#define mpeg_ts_header_get_continuityCounter(x) ((((x)[3]) & 0x0f))
#define mpeg_ts_header_set_continuityCounter(x, v) { (x)[3] = (((x)[3]) & 0xf0) | ((v) & 0x0f); }

#define sizeof_mpeg_ts_header (4)

// mpeg_ts_adaptation_field
typedef unsigned char mpeg_ts_adaptation_field_t;

#define mpeg_ts_adaptation_field_get_adaptationFieldLength(x) (((x)[0]))
#define mpeg_ts_adaptation_field_set_adaptationFieldLength(x, v) { (x)[0] = ((v) & 0xff); }
#define mpeg_ts_adaptation_field_get_discontinuityIndicator(x) (((((x)[1]) & 0x80) >> 7))
#define mpeg_ts_adaptation_field_set_discontinuityIndicator(x, v) { (x)[1] = (((x)[1]) & 0x7f) | (((v) << 7) & 0x80); }
#define mpeg_ts_adaptation_field_get_randomAccessIndicator(x) (((((x)[1]) & 0x40) >> 6))
#define mpeg_ts_adaptation_field_set_randomAccessIndicator(x, v) { (x)[1] = (((x)[1]) & 0xbf) | (((v) << 6) & 0x40); }
#define mpeg_ts_adaptation_field_get_esPriorityIndicator(x) (((((x)[1]) & 0x20) >> 5))
#define mpeg_ts_adaptation_field_set_esPriorityIndicator(x, v) { (x)[1] = (((x)[1]) & 0xdf) | (((v) << 5) & 0x20); }
#define mpeg_ts_adaptation_field_get_pcrFlag(x) (((((x)[1]) & 0x10) >> 4))
#define mpeg_ts_adaptation_field_set_pcrFlag(x, v) { (x)[1] = (((x)[1]) & 0xef) | (((v) << 4) & 0x10); }
#define mpeg_ts_adaptation_field_get_opcrFlag(x) (((((x)[1]) & 0x08) >> 3))
#define mpeg_ts_adaptation_field_set_opcrFlag(x, v) { (x)[1] = (((x)[1]) & 0xf7) | (((v) << 3) & 0x08); }
#define mpeg_ts_adaptation_field_get_splicingPointFlag(x) (((((x)[1]) & 0x04) >> 2))
#define mpeg_ts_adaptation_field_set_splicingPointFlag(x, v) { (x)[1] = (((x)[1]) & 0xfb) | (((v) << 2) & 0x04); }
#define mpeg_ts_adaptation_field_get_transportPrivateDataFlag(x) (((((x)[1]) & 0x02) >> 1))
#define mpeg_ts_adaptation_field_set_transportPrivateDataFlag(x, v) { (x)[1] = (((x)[1]) & 0xfd) | (((v) << 1) & 0x02); }
#define mpeg_ts_adaptation_field_get_adaptationFieldExtensionFlag(x) ((((x)[1]) & 0x01))
#define mpeg_ts_adaptation_field_set_adaptationFieldExtensionFlag(x, v) { (x)[1] = (((x)[1]) & 0xfe) | ((v) & 0x01); }

#define sizeof_mpeg_ts_adaptation_field (2)

// pes_header
typedef unsigned char pes_header_t;

#define pes_header_get_prefix(x) ((((x)[0]) << 16) | (((x)[1]) << 8) | ((x)[2]))
#define pes_header_set_prefix(x, v) { (x)[0] = (((v) >> 16) & 0xff); (x)[1] = (((v) >> 8) & 0xff); (x)[2] = ((v) & 0xff); }
#define pes_header_get_streamId(x) (((x)[3]))
#define pes_header_set_streamId(x, v) { (x)[3] = ((v) & 0xff); }
#define pes_header_get_pesPacketLength(x) ((((x)[4]) << 8) | ((x)[5]))
#define pes_header_set_pesPacketLength(x, v) { (x)[4] = (((v) >> 8) & 0xff); (x)[5] = ((v) & 0xff); }

#define sizeof_pes_header (6)

// pes_optional_header
typedef unsigned char pes_optional_header_t;

#define pes_optional_header_get_markerBits(x) (((((x)[0]) & 0xc0) >> 6))
#define pes_optional_header_set_markerBits(x, v) { (x)[0] = (((x)[0]) & 0x3f) | (((v) << 6) & 0xc0); }
#define pes_optional_header_get_scramblingControls(x) (((((x)[0]) & 0x30) >> 4))
#define pes_optional_header_set_scramblingControls(x, v) { (x)[0] = (((x)[0]) & 0xcf) | (((v) << 4) & 0x30); }
#define pes_optional_header_get_priority(x) (((((x)[0]) & 0x08) >> 3))
#define pes_optional_header_set_priority(x, v) { (x)[0] = (((x)[0]) & 0xf7) | (((v) << 3) & 0x08); }
#define pes_optional_header_get_dataAlignmentIndicator(x) (((((x)[0]) & 0x04) >> 2))
#define pes_optional_header_set_dataAlignmentIndicator(x, v) { (x)[0] = (((x)[0]) & 0xfb) | (((v) << 2) & 0x04); }
#define pes_optional_header_get_copyright(x) (((((x)[0]) & 0x02) >> 1))
#define pes_optional_header_set_copyright(x, v) { (x)[0] = (((x)[0]) & 0xfd) | (((v) << 1) & 0x02); }
#define pes_optional_header_get_originalOrCopy(x) ((((x)[0]) & 0x01))
#define pes_optional_header_set_originalOrCopy(x, v) { (x)[0] = (((x)[0]) & 0xfe) | ((v) & 0x01); }
#define pes_optional_header_get_ptsFlag(x) (((((x)[1]) & 0x80) >> 7))
#define pes_optional_header_set_ptsFlag(x, v) { (x)[1] = (((x)[1]) & 0x7f) | (((v) << 7) & 0x80); }
#define pes_optional_header_get_dtsFlag(x) (((((x)[1]) & 0x40) >> 6))
#define pes_optional_header_set_dtsFlag(x, v) { (x)[1] = (((x)[1]) & 0xbf) | (((v) << 6) & 0x40); }
#define pes_optional_header_get_escrFlag(x) (((((x)[1]) & 0x20) >> 5))
#define pes_optional_header_set_escrFlag(x, v) { (x)[1] = (((x)[1]) & 0xdf) | (((v) << 5) & 0x20); }
#define pes_optional_header_get_esRateFlag(x) (((((x)[1]) & 0x10) >> 4))
#define pes_optional_header_set_esRateFlag(x, v) { (x)[1] = (((x)[1]) & 0xef) | (((v) << 4) & 0x10); }
#define pes_optional_header_get_dsmTrickModeFlag(x) (((((x)[1]) & 0x08) >> 3))
#define pes_optional_header_set_dsmTrickModeFlag(x, v) { (x)[1] = (((x)[1]) & 0xf7) | (((v) << 3) & 0x08); }
#define pes_optional_header_get_additionalCopyInfoFlag(x) (((((x)[1]) & 0x04) >> 2))
#define pes_optional_header_set_additionalCopyInfoFlag(x, v) { (x)[1] = (((x)[1]) & 0xfb) | (((v) << 2) & 0x04); }
#define pes_optional_header_get_crcFlag(x) (((((x)[1]) & 0x02) >> 1))
#define pes_optional_header_set_crcFlag(x, v) { (x)[1] = (((x)[1]) & 0xfd) | (((v) << 1) & 0x02); }
#define pes_optional_header_get_extensionFlag(x) ((((x)[1]) & 0x01))
#define pes_optional_header_set_extensionFlag(x, v) { (x)[1] = (((x)[1]) & 0xfe) | ((v) & 0x01); }
#define pes_optional_header_get_pesHeaderLength(x) (((x)[2]))
#define pes_optional_header_set_pesHeaderLength(x, v) { (x)[2] = ((v) & 0xff); }

#define sizeof_pes_optional_header (3)

// pcr
typedef unsigned char pcr_t;

#define pcr_get_pcr90kHzHigh(x) ((((x)[0]) << 9) | (((x)[1]) << 1) | ((((x)[2]) & 0x80) >> 7))
#define pcr_set_pcr90kHzHigh(x, v) { (x)[0] = (((v) >> 9) & 0xff); (x)[1] = (((v) >> 1) & 0xff); (x)[2] = (((x)[2]) & 0x7f) | (((v) << 7) & 0x80); }
#define pcr_get_pcr90kHzLow(x) (((((x)[2]) & 0x7f) << 9) | (((x)[3]) << 1) | ((((x)[4]) & 0x80) >> 7))
#define pcr_set_pcr90kHzLow(x, v) { (x)[2] = (((x)[2]) & 0x80) | (((v) >> 9) & 0x7f); (x)[3] = (((v) >> 1) & 0xff); (x)[4] = (((x)[4]) & 0x7f) | (((v) << 7) & 0x80); }
#define pcr_get_padding(x) (((((x)[4]) & 0x7e) >> 1))
#define pcr_set_padding(x, v) { (x)[4] = (((x)[4]) & 0x81) | (((v) << 1) & 0x7e); }
#define pcr_get_pcr27kHz(x) (((((x)[4]) & 0x01) << 8) | ((x)[5]))
#define pcr_set_pcr27kHz(x, v) { (x)[4] = (((x)[4]) & 0xfe) | (((v) >> 8) & 0x01); (x)[5] = ((v) & 0xff); }

#define sizeof_pcr (6)

// pts
typedef unsigned char pts_t;

#define pts_get_pad1(x) (((((x)[0]) & 0xf0) >> 4))
#define pts_set_pad1(x, v) { (x)[0] = (((x)[0]) & 0x0f) | (((v) << 4) & 0xf0); }
#define pts_get_high(x) (((((x)[0]) & 0x0e) >> 1))
#define pts_set_high(x, v) { (x)[0] = (((x)[0]) & 0xf1) | (((v) << 1) & 0x0e); }
#define pts_get_marker1(x) ((((x)[0]) & 0x01))
#define pts_set_marker1(x, v) { (x)[0] = (((x)[0]) & 0xfe) | ((v) & 0x01); }
#define pts_get_medium(x) ((((x)[1]) << 7) | ((((x)[2]) & 0xfe) >> 1))
#define pts_set_medium(x, v) { (x)[1] = (((v) >> 7) & 0xff); (x)[2] = (((x)[2]) & 0x01) | (((v) << 1) & 0xfe); }
#define pts_get_marker2(x) ((((x)[2]) & 0x01))
#define pts_set_marker2(x, v) { (x)[2] = (((x)[2]) & 0xfe) | ((v) & 0x01); }
#define pts_get_low(x) ((((x)[3]) << 7) | ((((x)[4]) & 0xfe) >> 1))
#define pts_set_low(x, v) { (x)[3] = (((v) >> 7) & 0xff); (x)[4] = (((x)[4]) & 0x01) | (((v) << 1) & 0xfe); }
#define pts_get_marker3(x) ((((x)[4]) & 0x01))
#define pts_set_marker3(x, v) { (x)[4] = (((x)[4]) & 0xfe) | ((v) & 0x01); }

#define sizeof_pts (5)

// pat
typedef unsigned char pat_t;

#define pat_get_pointerField(x) (((x)[0]))
#define pat_set_pointerField(x, v) { (x)[0] = ((v) & 0xff); }
#define pat_get_tableId(x) (((x)[1]))
#define pat_set_tableId(x, v) { (x)[1] = ((v) & 0xff); }
#define pat_get_sectionSyntaxIndicator(x) (((((x)[2]) & 0x80) >> 7))
#define pat_set_sectionSyntaxIndicator(x, v) { (x)[2] = (((x)[2]) & 0x7f) | (((v) << 7) & 0x80); }
#define pat_get_zero(x) (((((x)[2]) & 0x40) >> 6))
#define pat_set_zero(x, v) { (x)[2] = (((x)[2]) & 0xbf) | (((v) << 6) & 0x40); }
#define pat_get_reserved1(x) (((((x)[2]) & 0x30) >> 4))
#define pat_set_reserved1(x, v) { (x)[2] = (((x)[2]) & 0xcf) | (((v) << 4) & 0x30); }
#define pat_get_reserved2(x) (((((x)[2]) & 0x0c) >> 2))
#define pat_set_reserved2(x, v) { (x)[2] = (((x)[2]) & 0xf3) | (((v) << 2) & 0x0c); }
#define pat_get_sectionLength(x) (((((x)[2]) & 0x03) << 8) | ((x)[3]))
#define pat_set_sectionLength(x, v) { (x)[2] = (((x)[2]) & 0xfc) | (((v) >> 8) & 0x03); (x)[3] = ((v) & 0xff); }
#define pat_get_tranportStreamId(x) ((((x)[4]) << 8) | ((x)[5]))
#define pat_set_tranportStreamId(x, v) { (x)[4] = (((v) >> 8) & 0xff); (x)[5] = ((v) & 0xff); }
#define pat_get_reserved3(x) (((((x)[6]) & 0xc0) >> 6))
#define pat_set_reserved3(x, v) { (x)[6] = (((x)[6]) & 0x3f) | (((v) << 6) & 0xc0); }
#define pat_get_versionNumber(x) (((((x)[6]) & 0x3e) >> 1))
#define pat_set_versionNumber(x, v) { (x)[6] = (((x)[6]) & 0xc1) | (((v) << 1) & 0x3e); }
#define pat_get_currentNextIndicator(x) ((((x)[6]) & 0x01))
#define pat_set_currentNextIndicator(x, v) { (x)[6] = (((x)[6]) & 0xfe) | ((v) & 0x01); }
#define pat_get_sectionNumber(x) (((x)[7]))
#define pat_set_sectionNumber(x, v) { (x)[7] = ((v) & 0xff); }
#define pat_get_lastSectionNumber(x) (((x)[8]))
#define pat_set_lastSectionNumber(x, v) { (x)[8] = ((v) & 0xff); }

#define sizeof_pat (9)

// pat_entry
typedef unsigned char pat_entry_t;

#define pat_entry_get_programNumber(x) ((((x)[0]) << 8) | ((x)[1]))
#define pat_entry_set_programNumber(x, v) { (x)[0] = (((v) >> 8) & 0xff); (x)[1] = ((v) & 0xff); }
#define pat_entry_get_reserved(x) (((((x)[2]) & 0xe0) >> 5))
#define pat_entry_set_reserved(x, v) { (x)[2] = (((x)[2]) & 0x1f) | (((v) << 5) & 0xe0); }
#define pat_entry_get_programPID(x) (((((x)[2]) & 0x1f) << 8) | ((x)[3]))
#define pat_entry_set_programPID(x, v) { (x)[2] = (((x)[2]) & 0xe0) | (((v) >> 8) & 0x1f); (x)[3] = ((v) & 0xff); }

#define sizeof_pat_entry (4)

// pmt
typedef unsigned char pmt_t;

#define pmt_get_pointerField(x) (((x)[0]))
#define pmt_set_pointerField(x, v) { (x)[0] = ((v) & 0xff); }
#define pmt_get_tableId(x) (((x)[1]))
#define pmt_set_tableId(x, v) { (x)[1] = ((v) & 0xff); }
#define pmt_get_sectionSyntaxIndicator(x) (((((x)[2]) & 0x80) >> 7))
#define pmt_set_sectionSyntaxIndicator(x, v) { (x)[2] = (((x)[2]) & 0x7f) | (((v) << 7) & 0x80); }
#define pmt_get_zero(x) (((((x)[2]) & 0x40) >> 6))
#define pmt_set_zero(x, v) { (x)[2] = (((x)[2]) & 0xbf) | (((v) << 6) & 0x40); }
#define pmt_get_reserved1(x) (((((x)[2]) & 0x30) >> 4))
#define pmt_set_reserved1(x, v) { (x)[2] = (((x)[2]) & 0xcf) | (((v) << 4) & 0x30); }
#define pmt_get_reserved2(x) (((((x)[2]) & 0x0c) >> 2))
#define pmt_set_reserved2(x, v) { (x)[2] = (((x)[2]) & 0xf3) | (((v) << 2) & 0x0c); }
#define pmt_get_sectionLength(x) (((((x)[2]) & 0x03) << 8) | ((x)[3]))
#define pmt_set_sectionLength(x, v) { (x)[2] = (((x)[2]) & 0xfc) | (((v) >> 8) & 0x03); (x)[3] = ((v) & 0xff); }
#define pmt_get_programNumber(x) ((((x)[4]) << 8) | ((x)[5]))
#define pmt_set_programNumber(x, v) { (x)[4] = (((v) >> 8) & 0xff); (x)[5] = ((v) & 0xff); }
#define pmt_get_reserved3(x) (((((x)[6]) & 0xc0) >> 6))
#define pmt_set_reserved3(x, v) { (x)[6] = (((x)[6]) & 0x3f) | (((v) << 6) & 0xc0); }
#define pmt_get_versionNumber(x) (((((x)[6]) & 0x3e) >> 1))
#define pmt_set_versionNumber(x, v) { (x)[6] = (((x)[6]) & 0xc1) | (((v) << 1) & 0x3e); }
#define pmt_get_currentNextIndicator(x) ((((x)[6]) & 0x01))
#define pmt_set_currentNextIndicator(x, v) { (x)[6] = (((x)[6]) & 0xfe) | ((v) & 0x01); }
#define pmt_get_sectionNumber(x) (((x)[7]))
#define pmt_set_sectionNumber(x, v) { (x)[7] = ((v) & 0xff); }
#define pmt_get_lastSectionNumber(x) (((x)[8]))
#define pmt_set_lastSectionNumber(x, v) { (x)[8] = ((v) & 0xff); }
#define pmt_get_reserved4(x) (((((x)[9]) & 0xe0) >> 5))
#define pmt_set_reserved4(x, v) { (x)[9] = (((x)[9]) & 0x1f) | (((v) << 5) & 0xe0); }
#define pmt_get_pcrPID(x) (((((x)[9]) & 0x1f) << 8) | ((x)[10]))
#define pmt_set_pcrPID(x, v) { (x)[9] = (((x)[9]) & 0xe0) | (((v) >> 8) & 0x1f); (x)[10] = ((v) & 0xff); }
#define pmt_get_reserved5(x) (((((x)[11]) & 0xf0) >> 4))
#define pmt_set_reserved5(x, v) { (x)[11] = (((x)[11]) & 0x0f) | (((v) << 4) & 0xf0); }
#define pmt_get_reserved6(x) (((((x)[11]) & 0x0c) >> 2))
#define pmt_set_reserved6(x, v) { (x)[11] = (((x)[11]) & 0xf3) | (((v) << 2) & 0x0c); }
#define pmt_get_programInfoLength(x) (((((x)[11]) & 0x03) << 8) | ((x)[12]))
#define pmt_set_programInfoLength(x, v) { (x)[11] = (((x)[11]) & 0xfc) | (((v) >> 8) & 0x03); (x)[12] = ((v) & 0xff); }

#define sizeof_pmt (13)

// pmt_entry
typedef unsigned char pmt_entry_t;

#define pmt_entry_get_streamType(x) (((x)[0]))
#define pmt_entry_set_streamType(x, v) { (x)[0] = ((v) & 0xff); }
#define pmt_entry_get_Reserved1(x) (((((x)[1]) & 0xe0) >> 5))
#define pmt_entry_set_Reserved1(x, v) { (x)[1] = (((x)[1]) & 0x1f) | (((v) << 5) & 0xe0); }
#define pmt_entry_get_elementaryPID(x) (((((x)[1]) & 0x1f) << 8) | ((x)[2]))
#define pmt_entry_set_elementaryPID(x, v) { (x)[1] = (((x)[1]) & 0xe0) | (((v) >> 8) & 0x1f); (x)[2] = ((v) & 0xff); }
#define pmt_entry_get_Reserved2(x) (((((x)[3]) & 0xf0) >> 4))
#define pmt_entry_set_Reserved2(x, v) { (x)[3] = (((x)[3]) & 0x0f) | (((v) << 4) & 0xf0); }
#define pmt_entry_get_reserved3(x) (((((x)[3]) & 0x0c) >> 2))
#define pmt_entry_set_reserved3(x, v) { (x)[3] = (((x)[3]) & 0xf3) | (((v) << 2) & 0x0c); }
#define pmt_entry_get_esInfoLength(x) (((((x)[3]) & 0x03) << 8) | ((x)[4]))
#define pmt_entry_set_esInfoLength(x, v) { (x)[3] = (((x)[3]) & 0xfc) | (((v) >> 8) & 0x03); (x)[4] = ((v) & 0xff); }

#define sizeof_pmt_entry (5)

#endif // __MPEGTSSTRUCTS_H__
