#We still need to add more configuration to .env and change the configMapping accordingly, then make sure it's in /myconfig/
version: '3.1'
services:
  liveController:
    env_file: .env
    image: kaltura/live-controller:${VERSION}
    hostname: ${SERVER_NODE_HOST_NAME}
    volumes:
    - "${LOGS_DIR}/liveController/:/var/log/liveController/"
    - "content:/web/content/kLive/"
    container_name: liveController
volumes:
  content:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=pa-isilon2,nolock,soft,rw"
      device: ":/ifs/web2/content/kLive"